### ISSUE TITLE
Unable to run the example

### ISSUE THREAD

**Issue by YifeiLyu** [nimazareian/quadruped-rl-locomotion#1]
Hi, when I ran the test code using

`python train.py --run test --model_path ./models/2024-04-16_10-11-57-x=1_torque_ctrl_fixed_joint_range_5mill_iter_working_well/final_model.zip`

I got this error:

2024-05-23 23:29:42.261055: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-05-23 23:29:42.261132: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-05-23 23:29:42.262996: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-05-23 23:29:42.272652: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-05-23 23:29:44.090107: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/usr/local/lib/python3.10/dist-packages/stable_baselines3/common/save_util.py:167: UserWarning: Could not deserialize object clip_range. Consider using `custom_objects` argument to replace this object.
Exception: Can't get attribute '_function_setstate' on <module 'cloudpickle.cloudpickle' from '/usr/local/lib/python3.10/dist-packages/cloudpickle/cloudpickle.py'>
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/stable_baselines3/common/save_util.py:167: UserWarning: Could not deserialize object lr_schedule. Consider using `custom_objects` argument to replace this object.
Exception: Can't get attribute '_function_setstate' on <module 'cloudpickle.cloudpickle' from '/usr/local/lib/python3.10/dist-packages/cloudpickle/cloudpickle.py'>
  warnings.warn(
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
Traceback (most recent call last):
  File "/content/drive/MyDrive/Colab Notebooks/quadruped-rl-locomotion/train.py", line 187, in <module>
    test(args)
  File "/content/drive/MyDrive/Colab Notebooks/quadruped-rl-locomotion/train.py", line 94, in test
    model = PPO.load(path=model_path, env=env, verbose=1)
  File "/usr/local/lib/python3.10/dist-packages/stable_baselines3/common/base_class.py", line 717, in load
    check_for_correct_spaces(env, data["observation_space"], data["action_space"])
  File "/usr/local/lib/python3.10/dist-packages/stable_baselines3/common/utils.py", line 229, in check_for_correct_spaces
    raise ValueError(f"Observation spaces do not match: {observation_space} != {env.observation_space}")
ValueError: Observation spaces do not match: Box(-inf, inf, (45,), float64) != Box(-inf, inf, (48,), float64)

**Comment by mengkangli** [comment]
I came across the same situation. Have you solved the problem?

**Comment by nimazareian** [comment]
I think the `train.py` script has been updated with a few new observations since the model you're trying to use was trained. One option is to checkout an older commit and retrying to run the same command. Here's a commit that works on my end: 4756dee0ffe7b4e5e78a60195c47d5427998b2a6
